---
title: "bing2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls()) 
bingchild<-read.csv("bingdataR.csv", header=T)
str(bingchild)
```

```{r}
library(lme4)
library(readr)
library(tidyverse)
library(sjPlot)
library(ggthemes)
library(gridExtra)
library(reshape2)
library(car)
library(psych)
library("ggpubr")
library(dplyr)
describe(bingchild)

source("Roger_functions/diagnostic_fcns.r")
source("Roger_functions/glmm_stability.r")
source("Roger_functions/boot_glmm.r")
```
```{r}
#preprocessing of data, scale categorical variables and define others as factor
bingchild$z.trialno<-as.vector(scale(bingchild$trialno))
bingchild$z.age=as.vector(scale(bingchild$age))
bingchild$id=as.factor(bingchild$id)
bingchild$sex=as.factor(bingchild$sex)
bingchild$agecat=as.factor(bingchild$agecat)
bingchild$condition=as.factor(bingchild$condition)
bingchild$z.agemonths=as.vector(scale(bingchild$agemonths))


bingchild$agecat=relevel(bingchild$agecat, ref="three")
bingchild$condition=relevel(bingchild$condition, ref="causal")
summary(bingchild)

#coding dummy variables before centering the slopes
bingchild$sex.m<-as.numeric(bingchild$sex==levels(bingchild$sex)[2])
bingchild$condition.arbitrary<-as.numeric(bingchild$condition==levels(bingchild$condition)[2])
bingchild$agecat.four<-as.numeric(bingchild$agecat==levels(bingchild$agecat)[3])
bingchild$agecat.five<-as.numeric(bingchild$agecat==levels(bingchild$agecat)[2])
bingchild$agecat.six<-as.numeric(bingchild$agecat==levels(bingchild$agecat)[4]) 
levels(bingchild$agecat)
levels(bingchild$condition)
#centering the slopes
bingchild$sex.m.c<-bingchild$sex.m -mean(bingchild$sex.m)
bingchild$agecat.four.c=bingchild$agecat.four-mean(bingchild$agecat.four)
bingchild$agecat.five.c=bingchild$agecat.five-mean(bingchild$agecat.five)
bingchild$agecat.six.c=bingchild$agecat.six-mean(bingchild$agecat.six)
str(bingchild)
```

#Amanda asked to make a bing machine graph that is similar to the graph we had in ripped foil for children

#Scatterplot to see the performance in causal and arbitrary conditions across age in months
```{r}
#Running a separate model for the CI calculation.

#running a new model for CI predictions
contr<-glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=10000000))
full.CI=glmer(correct ~ z.agemonths*condition + z.trialno + sex + (1|id) + (1|boxtype) + (0+z.trialno|id),data=bingchild, family=binomial, control=contr)
```
```{r}
#Getting confidence intervals for fitted values

boot.res=boot.glmm.pred(model.res=full.CI, excl.warnings=T, nboots=1000, resol=129, level=0.95, use="z.agemonths", n.cores="all-1", para=T)#with para=T your computer will get very slow so I recommend using this option particularly when you don't need to work with the PC in parallel (the CI calculation will be a lot faster though)

boot.res$ci.estimates
boot.res$ci.predicted
save.image("bingmachine_child_CIs.RData")
load("bingmachine_child_CIs.RData")
```

```{r}

####Overall performance across age.
bingchild_separate <- bingchild %>%
  filter(!is.na(correct)) %>%
  group_by(id,  agemonths, condition) %>% 
  summarize(correct= mean(correct))%>%
  ungroup()%>%
  group_by(agemonths, condition)%>%
  add_count(correct)

plot.int=seq(from=min(bingchild_separate$agemonths),
             to=max(bingchild_separate$agemonths),length.out=129)

ci.data<-boot.res$ci.predicted #I reduced the number of values for the confidence intervals. did not match the actual data.
toDelete<- seq(2, nrow(ci.data),2)
ci.data<-ci.data[toDelete,]
ci.data

scatter.int <- ggplot(ci.data, aes(y = ci.data$fitted)) +
  geom_point(data=bingchild_separate, aes(x = agemonths, y = correct), size = bingchild_separate$n, alpha = 0.8) +
  facet_wrap(~condition) + geom_segment(data=data.frame(condition="causal"))+ geom_segment(data=data.frame(condition="arbitrary")) +
  geom_ribbon(data = ci.data%>%filter(condition=="causal"), aes(x = plot.int, y = ci.data$fitted, ymin = ci.data$lower.cl, ymax = ci.data$upper.cl, group = condition), fill = "grey", alpha = 0.5) +
  geom_line(data = ci.data%>%filter(condition=="causal"), aes(x = plot.int, y = ci.data$fitted), lty = 2) +
  geom_ribbon(data = ci.data%>%filter(condition=="arbitrary"), aes(x = plot.int, y = ci.data$fitted, ymin = ci.data$lower.cl, ymax = ci.data$upper.cl, group = condition), fill = "grey", alpha = 0.5) +
  geom_line(data = ci.data%>%filter(condition=="arbitrary"), aes(x = plot.int, y = ci.data$fitted), lty = 2) + scale_x_continuous(breaks = seq(from = 36, to = 84, by = 4)) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  xlab("Age in months") +
  ylab("Mean correct responses") +
  ylim(0, 1) +
  geom_hline(yintercept = 0.50, color = "red", linetype = "dashed")

scatter.int
```

